### ISSUE TITLE
Error installing json (1.8.0)

### ISSUE THREAD

**Issue by mattlindsey** [schneems/wicked_example#3]
mattlindsey@MATTs-MBP wicked_example (master) $ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 10.1.0
Installing i18n 0.6.4
Installing multi_json 1.7.7
Installing builder 3.0.4
Using erubis 2.7.0
Installing journey 1.0.4
Installing rack 1.4.5
Installing hike 1.2.3
Installing tilt 1.4.1
Installing mime-types 1.17.2
Installing polyglot 0.3.3
Installing arel 3.0.2
Installing tzinfo 0.3.31
Installing bcrypt-ruby 3.0.1 with native extensions
Installing coffee-script-source 1.2.0
Installing json 1.8.0 with native extensions
Installing thor 0.14.6
Installing libv8 3.3.10.4 with native extensions
Installing orm_adapter 0.0.6
Using bundler 1.13.6
Installing sass 3.1.15
Installing sqlite3 1.3.5 with native extensions
Installing activesupport 3.2.1
Installing execjs 1.3.0
Installing rack-cache 1.2
Installing rack-test 0.6.2
Installing rack-ssl 1.3.3
Installing warden 1.1.1
Installing sprockets 2.1.3
Installing treetop 1.4.10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

An error occurred while installing json (1.8.0), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.0'` succeeds before bundling.

mattlindsey@MATTs-MBP wicked_example (master) $ gem install json -v '1.8.0'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/json-1.8.0/ext/json/ext/generator
/Users/mattlindsey/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170505-87497-10cx3v6.rb extconf.rb
creating Makefile

current directory: /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/json-1.8.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/json-1.8.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/mattlindsey/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' (aka 'unsigned long (const char *, long)') [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

**Comment by schneems** [comment]
this app is SUPER old. I honestly forgot it existed. Probably want to change the json version in the Gemfile to something more recent https://rubygems.org/gems/json
